[package]
name = "litmus-translator"
version = "0.1.0"
edition = "2021"
authors = ["Jasper <jhwp2@cam.ac.uk>"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
